### ISSUE TITLE
Notifications api

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/idea-town-addon#2]
https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Alerts_and_Notifications

**Comment by lmorchard** [comment]
Possibly handy too: https://github.com/lmorchard/idea-town-addon/blob/8c18fe3b6ae48694e04060dcc4994624bf5f59b1/index.js#L93

I really liked the [Notification Box](https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Alerts_and_Notifications#Using_notification_box) UI, but had to jump through a few hoops in one of my projects to get it to work. [That code up there](https://github.com/lmorchard/idea-town-addon/blob/8c18fe3b6ae48694e04060dcc4994624bf5f59b1/index.js#L93) is basically it. It's a slight cross between old-style extensions and new-style addons

**Comment by meandavejustice** [comment]
Unless this changes from @johngruen or @bryanbell we are probably going to go the route of badges as the only route for notifications.
