### ISSUE TITLE
postmessage API events

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town-addon#9]
Communication with the website front-end using WebChannel.

We should talk about this, but some ideas for signals: 
- "are you installed" message
  - sent by website to gecko when the ideatown page is loaded
  - if the addon is installed, it will ping back a yes (or possibly some user info)
- "please install / uninstall this extension" message
  - sent by front-end when a user requests to add/remove an experiment?

**Comment by meandavejustice** [comment]
Considering this the place to track the conversion from dual channel `web-to-addon` to flat events. As discussed in #10
